/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef S3EGPUIMAGE_AUTODEFS_H
#define S3EGPUIMAGE_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_GPUIMAGE_NAME "s3eGPUImage"
#define S3E_EXT_GPUIMAGE_HASH 0x6bcefc1f

#endif /* !S3EGPUIMAGE_AUTODEFS_H */
