/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
/*
 * This file contains the automatically generated loader-side
 * functions that form part of the extension.
 *
 * This file is awlays compiled into all loaders but compiles
 * to nothing if this extension is not enabled in the loader
 * at build time.
 */
#include "IwDebug.h"
#include "s3eGPUImage_autodefs.h"
#include "s3eEdk.h"
#include "s3eGPUImage.h"
//Declarations of Init and Term functions
extern s3eResult s3eGPUImageInit();
extern void s3eGPUImageTerminate();


// On platforms that use a seperate UI/OS thread we can autowrap functions
// here.   Note that we can't use the S3E_USE_OS_THREAD define since this
// code is oftern build standalone, outside the main loader build.
#if defined I3D_OS_IPHONE || defined I3D_OS_OSX || defined I3D_OS_LINUX || defined I3D_OS_WINDOWS

static char * s3eGPUImageTake_wrap(s3eGPUImageEventDoIt evnt, void * userData)
{
    IwTrace(GPUIMAGE_VERBOSE, ("calling s3eGPUImage func on main thread: s3eGPUImageTake"));
    return (char *)(intptr_t)s3eEdkThreadRunOnOS((s3eEdkThreadFunc)s3eGPUImageTake, 2, evnt, userData);
}

#define s3eGPUImageTake s3eGPUImageTake_wrap

#endif

void s3eGPUImageRegisterExt()
{
    /* fill in the function pointer struct for this extension */
    void* funcPtrs[4];
    funcPtrs[0] = (void*)s3eGPUImageGetContext;
    funcPtrs[1] = (void*)s3eGPUImageTake;
    funcPtrs[2] = (void*)s3eMyGLGenTextures;
    funcPtrs[3] = (void*)s3eRegisterGlGenTexturesCB;

    /*
     * Flags that specify the extension's use of locking and stackswitching
     */
    int flags[4] = { 0 };

    /*
     * Register the extension
     */
    s3eEdkRegister("s3eGPUImage", funcPtrs, sizeof(funcPtrs), flags, s3eGPUImageInit, s3eGPUImageTerminate, 0);
}

#if !defined S3E_BUILD_S3ELOADER

#if defined S3E_EDK_USE_STATIC_INIT_ARRAY
int s3eGPUImageStaticInit()
{
    void** p = g_StaticInitArray;
    void* end = p + g_StaticArrayLen;
    while (*p) p++;
    if (p < end)
        *p = (void*)&s3eGPUImageRegisterExt;
    return 0;
}

int g_s3eGPUImageVal = s3eGPUImageStaticInit();

#elif defined S3E_EDK_USE_DLLS
S3E_EXTERN_C S3E_DLL_EXPORT void RegisterExt()
{
    s3eGPUImageRegisterExt();
}
#endif

#endif
